const ChatbotViewModel={data:null,initialized:false,userName:sessionStorage.getItem("portfolioChatbotUserName")||"",context:sessionStorage.getItem("portfolioChatbotContext")||"",history:JSON.parse(sessionStorage.getItem("portfolioChatbotHistory")||"[]"),expectingName:false,
async initialize(){if(this.initialized)return;const host=document.getElementById("portfolioChatbotHost");if(!host)return;try{host.innerHTML=await fetch("../View/Chatbot/chatbot.html").then(r=>r.text());this.data=await ChatbotModel.load();this.bind();this.initialized=true;this.restore();if(!this.history.length)this.greet()}catch(e){host.innerHTML="<p>Portfolio assistant is temporarily unavailable.</p>";console.error(e)}},
bind(){const l=document.getElementById("chatbotLauncher"),p=document.getElementById("chatbotPanel"),c=document.getElementById("chatbotClose"),f=document.getElementById("chatbotForm"),i=document.getElementById("chatbotInput");l?.addEventListener("click",()=>{const open=p.hidden;p.hidden=!open;l.setAttribute("aria-expanded",String(open));if(open)i?.focus()});c?.addEventListener("click",()=>{p.hidden=true;l.setAttribute("aria-expanded","false");l.focus()});f?.addEventListener("submit",e=>{e.preventDefault();const q=i.value.trim();if(q){i.value="";this.ask(q)}})},
greet(){this.addMessage("bot",this.userName?"Welcome back, "+this.userName+"! What would you like to know about my iOS experience, skills or projects?":"Hi! I’m Ayaz’s portfolio assistant. What’s your name?");this.expectingName=!this.userName;this.renderSuggestions()},
restore(){this.history.slice(-12).forEach(m=>this.addMessage(m.type,m.text,false));this.renderSuggestions()},
save(){sessionStorage.setItem("portfolioChatbotUserName",this.userName);sessionStorage.setItem("portfolioChatbotContext",this.context);sessionStorage.setItem("portfolioChatbotHistory",JSON.stringify(this.history.slice(-12)))},
renderSuggestions(){const wrap=document.getElementById("chatbotSuggestions"),items=["What is your Swift experience?","Show my iOS projects","Open my resume","How can I contact you?"];wrap.innerHTML=items.map(q=>'<button type="button" class="chatbot-suggestion">'+q+"</button>").join("");wrap.querySelectorAll(".chatbot-suggestion").forEach(b=>b.addEventListener("click",()=>this.ask(b.textContent)))},
ask(q){this.addMessage("user",q);if(this.expectingName&&!this.userName&&q.length<=60&&!/\?|^(what|how|tell|do|can|where|who)\b/i.test(q)){this.userName=q.replace(/[.!]+$/,"").trim();this.expectingName=false;this.save();this.addMessage("bot","Nice to meet you, "+this.userName+"! Ask me anything about Ayaz’s portfolio.");return}
const nav=this.findNavigation(q);if(nav){this.addMessage("bot",nav.text);this.save();setTimeout(()=>this.navigate(nav.target),120);return}
const search=this.searchPortfolio(q);if(search&&/\b(show|find|search|open|view)\b/i.test(q)){this.addMessage("bot",search.text);this.save();return}
const r=ChatbotMatcher.findAnswer(q,this.data.intents,this.context);let a=r.answer;if(this.userName&&r.matched&&!["name","thanks"].includes(r.intent))a=this.userName+", "+a.charAt(0).toLowerCase()+a.slice(1);this.context=q;this.addMessage("bot",a);this.save()},
findNavigation(q){const s=ChatbotMatcher.search(q,this.data.searchable||[]);const hit=s[0]?.item;if(!hit)return null;const explicit=/\b(open|show|view|go|take|navigate)\b/i.test(q);if(explicit||["contact","resume","github","linkedin"].some(x=>q.toLowerCase().includes(x))){const target=this.data.navigation[hit.id]||hit.target||hit;return target?{target,text:"Sure — opening "+hit.title+"."}:null}return null},
searchPortfolio(q){const hits=ChatbotMatcher.search(q,this.data.searchable||[]);if(!hits.length)return null;return{text:"I found: "+hits.slice(0,3).map(x=>x.item.title).join(", ")+".",hits}},
navigate(target){if(/^https?:\/\//i.test(target)){window.open(target,"_blank","noopener");return}if(target.startsWith("#"))document.querySelector(target)?.scrollIntoView({behavior:"smooth",block:"start"})},
addMessage(type,text,save=true){const box=document.getElementById("chatbotMessages");if(!box)return;const e=document.createElement("div");e.className="chatbot-message "+type;e.textContent=text;box.appendChild(e);box.scrollTop=box.scrollHeight;if(save){this.history.push({type,text});this.history=this.history.slice(-12);this.save()}}
};