const ChatbotViewModel={data:null,initialized:false,userName:sessionStorage.getItem("portfolioChatbotUserName")||"",context:sessionStorage.getItem("portfolioChatbotContext")||"",history:JSON.parse(sessionStorage.getItem("portfolioChatbotHistory")||"[]"),expectingName:false,
async initialize(){if(this.initialized)return;const host=document.getElementById("portfolioChatbotHost");if(!host)return;try{host.innerHTML=await fetch("../View/Chatbot/chatbot.html").then(r=>r.text());this.data=await ChatbotModel.load();this.bind();this.initialized=true;this.restore();if(!this.history.length)this.greet()}catch(e){host.innerHTML="";console.error(e)}},
bind(){const l=document.getElementById("chatbotLauncher"),p=document.getElementById("chatbotPanel"),c=document.getElementById("chatbotClose"),f=document.getElementById("chatbotForm"),i=document.getElementById("chatbotInput");l?.addEventListener("click",()=>{const open=p.hidden;p.hidden=!open;l.hidden=open;l.setAttribute("aria-expanded",String(open));if(open)i?.focus()});c?.addEventListener("click",()=>{p.hidden=true;l.hidden=false;l.setAttribute("aria-expanded","false");l.focus()});f?.addEventListener("submit",e=>{e.preventDefault();const q=i.value.trim();if(q){i.value="";this.ask(q)}})},
greet(){this.addMessage("bot",this.userName?"Welcome back, "+this.userName+"! What would you like to explore?":"Hi! I’m Ayaz’s portfolio assistant. What’s your name?");this.expectingName=!this.userName;this.renderSuggestions()},
restore(){this.history.slice(-12).forEach(m=>this.addMessage(m.type,m.text,false));this.renderSuggestions()},
save(){sessionStorage.setItem("portfolioChatbotUserName",this.userName);sessionStorage.setItem("portfolioChatbotContext",this.context);sessionStorage.setItem("portfolioChatbotHistory",JSON.stringify(this.history.slice(-12)))},
renderSuggestions(){const wrap=document.getElementById("chatbotSuggestions"),items=["About Me","Experience","Skills","Projects","Resume","Contact"];wrap.innerHTML=items.map(q=>'<button type="button" class="chatbot-suggestion">'+q+"</button>").join("");wrap.querySelectorAll(".chatbot-suggestion").forEach(b=>b.addEventListener("click",()=>this.ask(b.textContent)))},
async ask(q){this.addMessage("user",q);if(this.expectingName&&!this.userName&&q.length<=60&&!/\?|^(what|how|tell|do|can|where|who|show|open)\b/i.test(q)){this.userName=q.replace(/[.!]+$/,"").trim();this.expectingName=false;this.save();this.addMessage("bot","Nice to meet you, "+this.userName+"! What would you like to explore?");return}
const command=this.command(q);if(command){this.showTyping();setTimeout(()=>{this.hideTyping();this.addBot(command.text,command.actions||[]);if(command.target)this.navigate(command.target)},220);return}
const r=ChatbotMatcher.findAnswer(q,this.data.intents,this.context);if(!r.matched){this.logUnanswered(q);this.showTyping();setTimeout(()=>{this.hideTyping();this.addBot(r.answer,["Projects","Skills","Experience","Contact"])},220);return}
this.showTyping();setTimeout(()=>{this.hideTyping();let a=r.answer;if(this.userName&&!["name","thanks"].includes(r.intent))a=this.userName+", "+a.charAt(0).toLowerCase()+a.slice(1);this.context=q;this.addBot(a,this.relatedActions(r.intent));this.save()},220)},
command(q){const n=q.toLowerCase(),nav=this.data.navigation||{};if(/\b(compare|difference|versus|vs)\b/.test(n)&&/swift/.test(n)&&/objective/.test(n))return{text:"Here’s a quick comparison:",html:'<table class="chatbot-compare"><tr><th>Technology</th><th>Experience</th></tr><tr><td>Objective-C</td><td>10+ years</td></tr><tr><td>Swift</td><td>6+ years</td></tr><tr><td>SwiftUI</td><td>~1 year</td></tr></table>'};if(/\b(what can you do|help|options)\b/.test(n))return{text:"I can answer questions about Ayaz’s career, iOS skills, projects and experience, or open portfolio sections.",actions:["About Me","Experience","Skills","Projects","Resume","Contact"]};const map=[["resume","Resume"],["cv","Resume"],["github","GitHub"],["linkedin","LinkedIn"],["contact","Contact"],["projects","Projects"],["project","Projects"],["skills","Skills"],["experience","Experience"],["about me","About Me"],["articles","Articles"]];for(const [key,label] of map)if(n.includes(key)){const target=label==="Resume"?nav.resume:label==="GitHub"?nav.github:label==="LinkedIn"?nav.linkedin:(this.data.searchable||[]).find(x=>x.title.toLowerCase()===label.toLowerCase())?.target;return{text:"Sure — opening "+label+".",target,actions:label==="Resume"||label==="GitHub"||label==="LinkedIn"?[]:[label]}}return null},
relatedActions(intent){const map={swift:["SwiftUI","Objective-C"],objective_c:["Swift","Projects"],swiftui:["Swift","Projects"],projects:["Resume","GitHub"],experience:["Resume","Projects"],contact:["Resume","LinkedIn"],name:["Experience","Skills"]};return map[intent]||["Experience","Projects"]},
showTyping(){const e=document.getElementById("chatbotTyping");if(e)e.hidden=false},hideTyping(){const e=document.getElementById("chatbotTyping");if(e)e.hidden=true},
addBot(text,actions=[]){this.addMessage("bot",text);if(actions.length){const box=document.getElementById("chatbotMessages"),wrap=document.createElement("div");wrap.className="chatbot-actions";actions.forEach(a=>{const b=document.createElement("button");b.className="chatbot-action";b.type="button";b.textContent=a;b.onclick=()=>this.ask(a);wrap.appendChild(b)});box.appendChild(wrap);box.scrollTop=box.scrollHeight}},
searchPortfolio(q){return ChatbotMatcher.search(q,this.data.searchable||[])},
logUnanswered(q){const key="portfolioChatbotUnanswered";const list=JSON.parse(localStorage.getItem(key)||"[]");if(!list.includes(q))localStorage.setItem(key,JSON.stringify([...list,q].slice(-50)))},
navigate(target){if(!target)return;if(/^https?:\/\//i.test(target)){window.open(target,"_blank","noopener");return}document.querySelector(target)?.scrollIntoView({behavior:"smooth",block:"start"})},
addMessage(type,text,save=true){const box=document.getElementById("chatbotMessages");if(!box)return;const e=document.createElement("div");e.className="chatbot-message "+type;e.textContent=text;box.appendChild(e);box.scrollTop=box.scrollHeight;if(save){this.history.push({type,text});this.history=this.history.slice(-12);this.save()}}
};